exclude: ^docs/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-pyupgrade
        args: [--py310-plus]
      - id: nbqa-isort
      - id: nbqa-black
      - id: nbqa-flake8

  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.8
    hooks:
      - id: jupytext
        args: [--sync]
        files: ^notebooks/.+\.ipynb$
